name: savodhon
description: Savodhon — o'zbekcha savodxonlik ilovasi (So'z Ustasi).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_tts: ^4.2.5
  speech_to_text: ^7.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
